import type { CSSProperties } from 'react';

// Design tokens extraits tels quels du prototype original (App.jsx) pour
// garantir un rendu visuel identique apres la refonte en composants.
export const theme = {
  page: {
    minHeight: '100vh',
    background: '#0f1b2d',
    color: '#eef2f7',
    fontFamily: 'system-ui, sans-serif',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '40px 20px',
  } satisfies CSSProperties,
  card: {
    width: '100%',
    maxWidth: 420,
    background: '#16243a',
    borderRadius: 18,
    padding: 28,
    boxShadow: '0 10px 40px rgba(0,0,0,.35)',
  } satisfies CSSProperties,
  title: { fontSize: 30, fontWeight: 800, margin: '0 0 4px' } satisfies CSSProperties,
  sub: { color: '#9fb2c9', margin: '0 0 24px', fontSize: 15 } satisfies CSSProperties,
  label: { fontSize: 13, color: '#9fb2c9', margin: '12px 0 6px', display: 'block' } satisfies CSSProperties,
  input: {
    width: '100%',
    boxSizing: 'border-box',
    padding: '12px 14px',
    borderRadius: 12,
    border: '1px solid #2a3c58',
    background: '#0f1b2d',
    color: '#fff',
    fontSize: 15,
  } satisfies CSSProperties,
  row: { display: 'flex', gap: 10, marginTop: 6 } satisfies CSSProperties,
  chip: (active: boolean): CSSProperties => ({
    flex: 1,
    padding: '11px',
    borderRadius: 999,
    border: '1px solid #2a3c58',
    background: active ? '#3b82f6' : 'transparent',
    color: '#fff',
    fontWeight: 600,
    cursor: 'pointer',
  }),
  btn: {
    width: '100%',
    marginTop: 18,
    padding: '13px',
    borderRadius: 12,
    border: 'none',
    background: '#3b82f6',
    color: '#fff',
    fontWeight: 700,
    fontSize: 15,
    cursor: 'pointer',
  } satisfies CSSProperties,
  btnSecondary: {
    width: '100%',
    marginTop: 18,
    padding: '13px',
    borderRadius: 12,
    border: 'none',
    background: '#22344f',
    color: '#fff',
    fontWeight: 700,
    fontSize: 15,
    cursor: 'pointer',
  } satisfies CSSProperties,
  link: {
    marginTop: 14,
    background: 'none',
    border: 'none',
    color: '#9fb2c9',
    cursor: 'pointer',
    fontSize: 14,
    width: '100%',
  } satisfies CSSProperties,
  err: { color: '#ff8a8a', fontSize: 14, marginTop: 12 } satisfies CSSProperties,
  ok: { color: '#7ee2a8', fontSize: 14, marginTop: 12 } satisfies CSSProperties,
  badge: {
    display: 'inline-block',
    padding: '6px 12px',
    borderRadius: 999,
    background: '#22344f',
    color: '#cfe0f5',
    fontSize: 13,
    marginBottom: 16,
  } satisfies CSSProperties,
  mission: {
    background: '#16243a',
    borderRadius: 14,
    padding: 18,
    marginTop: 12,
    textAlign: 'left',
  } satisfies CSSProperties,
};
